export { default as Header } from './Header/Header'
export { default as ProductCard } from './ProductCard/ProductCard'
export { default as CardsList } from './CardsList/CardsList'
export * from './Paginator/Paginator'
export { default as Thanks } from './Thanks/Thanks'
export { default as CartList } from './CartList/CartList'
export { default as ProductCart } from './ProductCart/ProductCart'
export { default as OrderForm } from './OrderForm/OrderForm'
